name = "realthx1/mock_data_store"
version = "0.1.0"
description = "Complete mock implementation of DataStoreService"
authors = ["realthx1"]
repository = "https://github.com/realthx1/mock-data-store"
license = "MIT"
includes = ["src/**/*", "pesde.toml", "README.md", "LICENSE", ".luaurc"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
analyze = ".lune/analyze.luau"
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
selene = { name = "pesde/selene", version = "^0.30.1", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.63.0", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
